### ISSUE TITLE
 cmake -DCMAKE_BUILD_TYPE=Release -DLIBTYPE=SHARED .  ERROR

### ISSUE THREAD

**Issue by lwluowei** [aristanetworks/ctypegen#10]
when i  am executing cmake -DCMAKE_BUILD_TYPE=Release -DLIBTYPE=SHARED .
I got the errors as follows:

-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.29.30133.0
-- The CXX compiler identification is MSVC 19.29.30133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find LibLZMA (missing: LIBLZMA_LIBRARY LIBLZMA_INCLUDE_DIR LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET)
-- Found ZLIB: C:/Program Files (x86)/zlib/lib/zlib.lib (found version "1.2.11")
-- Found Python2: C:/Python27/libs/python27.lib (found version "2.7.16") found components: Development Development.Module Development.Embed
-- Found Git: E:/Git/bin/git.exe (found version "2.24.0.windows.2")
-- Version from git tag: 814261c1deb101c87ff1c4c2e387a552301f57f9
-- Version: 814261c1deb101c87ff1c4c2e387a552301f57f9
CMake Warning at CMakeLists.txt:160 (message):
  no LZMA support found

-- Configuring done

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LTHREADDB
 linked by target "procman" in directory C:/Users/luowei7/pstack

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by peadar** [comment]
Hi lwluowei,
I see you're trying to build this on Windows with Visual Studio. Sorry, but this package is entirely Linux/UNIX-centric - It works with ELF binaries containing DWARF debug information. It's not going to work on windows without major surgery, I'm afraid.
