### ISSUE TITLE
Question about license header

### ISSUE THREAD

**Issue by rnadomname111111** [aristanetworks/ctypegen#11]
Hello! 
Is code Apache Licensed? 
But why ctypegen includes such header
     
Arista Networks, Inc. **Confidential and Proprietary**.
https://github.com/aristanetworks/ctypegen/blob/e424bbe83b9bc45cb209f3df193108eb8d9a9831/CTypeGen/__init__.py#L1691

**Comment by peadar** [comment]
The code is indeed Apache licensed.
ctypegen uses that text as a prelude to the code it generates - leaving it
in the published ctypegen source was an oversight on my part. I will remove
that text from the public repo.
Thanks for reporting!
