### ISSUE TITLE
Compile Error in WSL2

### ISSUE THREAD

**Issue by shish456** [aristanetworks/ctypegen#12]
I'm having some issues compiling in WSL2. The first issue I had was that the ctypegen script and CTypeGen directory have the same name, which isn't allowed in Windows. I fixed that by renaming ctypegen to ctypegen2 and fixing the name in setup.py. Now I'm running into the compile error seen below. I suspect it's due to the python exception, "RuntimeError:  read from null reader", but haven't debugged further. Any ideas?

> user@machine /mnt/c/Users/user/src $ make setup
make -C setup
make[1]: Entering directory '/mnt/c/Users/user'
cd ctypegen && make
make[2]: Entering directory '/mnt/c/Users/user/ctypegen'
env CFLAGS="-g --std=c++14" PYTHONPATH=/mnt/c/Users/user/ctypegen python ./setup.py build
running build
running build_py
running build_ext
building 'libCTypeGen' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -g --std=c++14 -fPIC -I/usr/local/include -I/usr/include/python2.7 -c CTypeGen.cpp -o build/temp.linux-x86_64-2.7/CTypeGen.o --std=c++17
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/include/python2.7/Python.h:88,
                 from CTypeGen.cpp:22:
/usr/include/python2.7/unicodeobject.h:534:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register PyObject *obj,     /* Object */
                        ^~~
/usr/include/python2.7/unicodeobject.h:553:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register PyObject *obj      /* Object */
                        ^~~
/usr/include/python2.7/unicodeobject.h:575:29: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register const wchar_t *w,  /* wchar_t buffer */
                             ^
/usr/include/python2.7/unicodeobject.h:593:23: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register wchar_t *w,        /* wchar_t buffer */
                       ^
In file included from /usr/include/python2.7/Python.h:97,
                 from CTypeGen.cpp:22:
/usr/include/python2.7/stringobject.h:173:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register PyObject *obj, /* string or Unicode object */
                        ^~~
/usr/include/python2.7/stringobject.h:174:21: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register char **s,  /* pointer to buffer variable */
                     ^
/usr/include/python2.7/stringobject.h:175:26: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register Py_ssize_t *len /* pointer to length variable or NULL
                          ^~~
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -g --std=c++14 build/temp.linux-x86_64-2.7/CTypeGen.o -L/usr/local/lib -Wl,-R/usr/local/lib -ldwelf -o build/lib.linux-x86_64-2.7/libCTypeGen.so
building 'libCTypeMock' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -g --std=c++14 -fPIC -I/usr/local/include -I/usr/include/python2.7 -c cmock.cpp -o build/temp.linux-x86_64-2.7/cmock.o --std=c++17
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/include/python2.7/Python.h:88,
                 from cmock.cpp:22:
/usr/include/python2.7/unicodeobject.h:534:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register PyObject *obj,     /* Object */
                        ^~~
/usr/include/python2.7/unicodeobject.h:553:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register PyObject *obj      /* Object */
                        ^~~
/usr/include/python2.7/unicodeobject.h:575:29: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register const wchar_t *w,  /* wchar_t buffer */
                             ^
/usr/include/python2.7/unicodeobject.h:593:23: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register wchar_t *w,        /* wchar_t buffer */
                       ^
In file included from /usr/include/python2.7/Python.h:97,
                 from cmock.cpp:22:
/usr/include/python2.7/stringobject.h:173:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register PyObject *obj, /* string or Unicode object */
                        ^~~
/usr/include/python2.7/stringobject.h:174:21: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register char **s,  /* pointer to buffer variable */
                     ^
/usr/include/python2.7/stringobject.h:175:26: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register Py_ssize_t *len /* pointer to length variable or NULL
                          ^~~
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -g --std=c++14 -fPIC -I/usr/local/include -I/usr/include/python2.7 -c thunk-x86_64.s -o build/temp.linux-x86_64-2.7/thunk-x86_64.o --std=c++17
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -g --std=c++14 build/temp.linux-x86_64-2.7/cmock.o build/temp.linux-x86_64-2.7/thunk-x86_64.o -L/usr/local/lib -Wl,-R/usr/local/lib -ldwelf -o build/lib.linux-x86_64-2.7/libCTypeMock.so
running build_scripts
creating build/scripts-2.7
copying and adjusting ctypegen2 -> build/scripts-2.7
cc -O0 -g -fPIC -fno-eliminate-unused-debug-types -g3   -c -o dbghelper.o dbghelper.c
cc -g --shared -o libdbghelper.so dbghelper.o
PYTHONPATH=/mnt/c/Users/user/ctypegen:`echo /mnt/c/Users/user/ctypegen/build/lib*` python ./generateLibc.py libc.so.6 CMock/libc.py || echo '(Ignore Exception above)'
warning: no support configured for compressed debug info in section .debug_info of /usr/lib/debug/.build-id/18/b9a9a8c523e5cfe5b5d946d605d09242f09798.debug
Traceback (most recent call last):
  File "./generateLibc.py", line 78, in <module>
    macroFiles='dbghelper.c',
  File "/mnt/c/Users/user/ctypegen/CTypeGen/__init__.py", line 1659, in generate
    namespaceFilter, macroFiles, trailer )
  File "/mnt/c/Users/user/ctypegen/CTypeGen/__init__.py", line 1785, in generateDwarf
    globalVars, deepInspect, namelessEnums, namespaceFilter )
  File "/mnt/c/Users/user/ctypegen/CTypeGen/__init__.py", line 1271, in __init__
    for u in dwarf.units():
RuntimeError:  read from null reader
(Ignore Exception above)
echo "Built for python"
Built for python
make[2]: Leaving directory '/mnt/c/Users/user/ctypegen'
cd ctypegen && sudo make install
env CFLAGS="-g --std=c++14" PYTHONPATH= /usr/bin/python  ./setup.py install
running install
running build
running build_py
running build_ext
running build_scripts
running install_lib
creating /usr/local/lib/python2.7/dist-packages/CMock
copying build/lib.linux-x86_64-2.7/CMock/helpers.py -> /usr/local/lib/python2.7/dist-packages/CMock
copying build/lib.linux-x86_64-2.7/CMock/__init__.py -> /usr/local/lib/python2.7/dist-packages/CMock
creating /usr/local/lib/python2.7/dist-packages/CTypeGen
copying build/lib.linux-x86_64-2.7/CTypeGen/expression.py -> /usr/local/lib/python2.7/dist-packages/CTypeGen
copying build/lib.linux-x86_64-2.7/CTypeGen/__init__.py -> /usr/local/lib/python2.7/dist-packages/CTypeGen
copying build/lib.linux-x86_64-2.7/CTypeGenRun.py -> /usr/local/lib/python2.7/dist-packages
copying build/lib.linux-x86_64-2.7/libCTypeGen.so -> /usr/local/lib/python2.7/dist-packages
copying build/lib.linux-x86_64-2.7/libCTypeMock.so -> /usr/local/lib/python2.7/dist-packages
byte-compiling /usr/local/lib/python2.7/dist-packages/CMock/helpers.py to helpers.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/CMock/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/CTypeGen/expression.py to expression.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/CTypeGen/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/CTypeGenRun.py to CTypeGenRun.pyc
running install_scripts
copying build/scripts-2.7/ctypegen2 -> /usr/local/bin
changing mode of /usr/local/bin/ctypegen2 to 777
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/CTypeGen-0.9.egg-info
cd ctypegen && make test
make[2]: Entering directory '/mnt/c/Users/user/ctypegen'
PYTHONPATH=/mnt/c/Users/user/ctypegen:`echo /mnt/c/Users/user/ctypegen/build/lib*` make -C test
make[3]: Entering directory '/mnt/c/Users/user/ctypegen/test'
cc -g3 -fPIC   -c -o CTypeSanityC.o CTypeSanityC.c
g++ -g3 -fPIC   -c -o CTypeSanity.o CTypeSanity.cpp
g++ -shared -o CTypeSanity CTypeSanityC.o CTypeSanity.o
g++ -g3 -fPIC   -c -o MockTest.o MockTest.cpp
g++ -g3 -fPIC   -c -o MockTestExtern.o MockTestExtern.cpp
g++ -shared -o MockTest MockTest.o MockTestExtern.o
cc -g3 -fPIC   -c -o PreMockTest.o PreMockTest.c
cc -g3 -fPIC   -c -o PreMockTestExtern.o PreMockTestExtern.c
g++ -shared -o libPreMockTest.so PreMockTest.o PreMockTestExtern.o
cc -g3 -fPIC   -c -o ChainTest.o ChainTest.c
cc -g3 -fPIC   -c -o ChainTestExtern.o ChainTestExtern.c
g++ -shared -o libChainTest.so ChainTest.o ChainTestExtern.o
cc -g3 -fPIC   -c -o FOpenTest.o FOpenTest.c
g++ -shared -o libFOpenTest.so FOpenTest.o
cc -g3 -fPIC   -c -o GreedyTest.o GreedyTest.c
g++ -g3 -fPIC   -c -o GreedyTestCpp.o GreedyTestCpp.cpp
g++ -shared -o libGreedyTest.so GreedyTest.o GreedyTestCpp.o
g++ -fshort-enums -fPIC -g   -c -o EnumTest.o EnumTest.cpp
g++ -shared -o libEnumTest.so EnumTest.o
g++ -g3 -fPIC   -c -o Supply.o Supply.cpp
g++ -shared -o libSupply.so Supply.o
g++ -g3 -fPIC   -c -o Demand.o Demand.cpp
g++ -shared -o libDemand.so Demand.o
python ./MockTest.py ./MockTest
generated and tested proggen
checking the C implementation does what it should before we poke around
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8f28)
returned 1, i is now 2
checking the mocked behaviour works on installation
this is the real g 42/forty-two
mocked function! got args: i(<type 'int'>)=1, s(<type 'str'>)=hello, iptr(<class 'proggen.LP_c_int'>)=1
returned 100, i is now 101
checking we can disable the mock
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8f28)
returned 1, i is now 2
Check that disabling an already disabled context manager does notinterfere with another.
this is the real g 42/forty-two
mocked function! got args: i(<type 'int'>)=1, s(<type 'str'>)=hello, iptr(<class 'proggen.LP_c_int'>)=1
returned 100, i is now 101
Check context manager in a loop with GC
this is the real g 42/forty-two
mocked function! got args: i(<type 'int'>)=1, s(<type 'str'>)=hello, iptr(<class 'proggen.LP_c_int'>)=1
returned 100, i is now 101
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8f28)
returned 1, i is now 2
this is the real g 42/forty-two
mocked function! got args: i(<type 'int'>)=1, s(<type 'str'>)=hello, iptr(<class 'proggen.LP_c_int'>)=1
returned 100, i is now 101
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8f28)
returned 1, i is now 2
this is the real g 42/forty-two
mocked function! got args: i(<type 'int'>)=1, s(<type 'str'>)=hello, iptr(<class 'proggen.LP_c_int'>)=1
returned 100, i is now 101
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8f28)
returned 1, i is now 2
this is the real g 42/forty-two
mocked function! got args: i(<type 'int'>)=1, s(<type 'str'>)=hello, iptr(<class 'proggen.LP_c_int'>)=1
returned 100, i is now 101
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8f28)
returned 1, i is now 2
this is the real g 42/forty-two
mocked function! got args: i(<type 'int'>)=1, s(<type 'str'>)=hello, iptr(<class 'proggen.LP_c_int'>)=1
returned 100, i is now 101
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8f28)
returned 1, i is now 2
this is the real g 42/forty-two
mocked function! got args: i(<type 'int'>)=1, s(<type 'str'>)=hello, iptr(<class 'proggen.LP_c_int'>)=1
returned 100, i is now 101
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8f28)
returned 1, i is now 2
this is the real g 42/forty-two
mocked function! got args: i(<type 'int'>)=1, s(<type 'str'>)=hello, iptr(<class 'proggen.LP_c_int'>)=1
returned 100, i is now 101
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8f28)
returned 1, i is now 2
this is the real g 42/forty-two
mocked function! got args: i(<type 'int'>)=1, s(<type 'str'>)=hello, iptr(<class 'proggen.LP_c_int'>)=1
returned 100, i is now 101
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8f28)
returned 1, i is now 2
check mocked member function
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8a28)
returned 1, i is now 2
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8a28)
returned 1, i is now 2
this is the real g 42/forty-two
returned 100, i is now 101
this is the real g 42/forty-two
the real f(1, hello, 0x7ffdc84b8a28)
returned 1, i is now 2
checking we can re-enable the mock
this is the real g 42/forty-two
mocked function! got args: i(<type 'int'>)=1, s(<type 'str'>)=hello, iptr(<class 'proggen.LP_c_int'>)=1
returned 100, i is now 101
checking STOMP mock
this is the mocked g 42/forty-two
this is the real g 42/forty-two
check calls to C++ functions via name demangling
Tests complete
python ./PreMockTest.py ./libPreMockTest.so
generated and tested premock
mock pre-call: received ival of 22 replaced with 42
preF(0, hello world, 0x7ffd3904bb3c(42))
mock pre-call: received ival of 22 replaced with 42
preF(0, hello world, 0x7ffd3904bb3c(42))
recursion depth: 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, done
python ./CTypeGenSanity.py ./CTypeSanity
warning: CTypeGen.generate requires a list of ELF images as its first argument
warning: no type found for NoSuchType
warning: variable NoSuchGlobal not found
warning: variable ie7 not found
warning: function nosuch_func not found
generated and tested CTypeSanity
compare aBitFieldPart5: 40/40
compare aBitFieldPart4: 30/30
compare aBool: False/False
compare aNestedUnion: {'notbar': 8589934593, 'bar': {'y': 2, 'x': 1}}/<CTypeSanity.union_Baz object at 0x7f9010603f80>
    compare notbar: 8589934593/8589934593
    compare bar: {'y': 2, 'x': 1}/<CTypeSanity.struct_Bar object at 0x7f90101e0050>
        compare y: 2/2
        compare x: 1/1
compare aCString: hello world/hello world
compare aOneDimensionalArrayOfChar: hello world/hello world
compare anEnum: 3/3
compare anIntPtr: 94170201990416/94170201990416
compare aDouble: 3.14159/3.14159265359
compare aSizeT: 1984/1984
compare aNestedStructurePointer: 94170201992272/<CTypeSanity.LP_struct_Bar object at 0x7f9010603f80>
compare bigEnum: 20014547599360/20014547599360
compare aBitFieldPart1: 100/100
compare aBitFieldPart3: 20/20
compare aBitFieldPart2: 10/10
compare aLong: 1234/1234
compare aChar: a/a
compare anInt: 3/3
compare aNestedStructure: {'y': 200, 'x': 100}/<CTypeSanity.struct_Bar object at 0x7f9010603f80>
    compare y: 200/200
    compare x: 100/100
Make sure calling the function pointer works correctly.
Checking macro definitions
Make sure 64-bit values are generated properly.
Verify we can specify and disambiguate namespaced and unnamespaced types
Verify we can distinguish structures and typedefs with the same name
Verify CFUNCTYPE generation
python ./ChainTest.py ./libChainTest.so
python ./PointersTest.py ./libFOpenTest.so
generated and tested ptrgen
Traceback (most recent call last):
  File "./PointersTest.py", line 28, in <module>
    libc, _ = CMock.helpers.getLibc()
  File "/mnt/c/Users/user/ctypegen/CMock/helpers.py", line 123, in getLibc
    import CMock.libc
ImportError: No module named libc
make[3]: *** [Makefile:73: check-pointers] Error 1
make[3]: Leaving directory '/mnt/c/Users/user/ctypegen/test'
make[2]: *** [Makefile:30: test] Error 2
make[2]: Leaving directory '/mnt/c/Users/user/ctypegen'
make[1]: *** [Makefile:11: .ctypegendone] Error 2
make[1]: Leaving directory '/mnt/c/Users/user'
make: *** [Makefile:18: setup] Error 2
user@machine /mnt/c/Users/user/src $

**Comment by SBmEX1G3** [comment]
Based on some cmake output I saw from pstack, installing some combinations of these packages fixed the issue:
