### ISSUE TITLE
libCTypeGen.so: undefined symbol: lzma_stream_footer_decode

### ISSUE THREAD

**Issue by sbryskyi** [aristanetworks/ctypegen#2]
Hi there! 
Thanks for your work and for making it public.

I've faced some strange linking? issue while setting up libCTypeGen

I'd appreciate any ideas on how to resolve it.

`make test
make -C test
make[1]: Entering directory '/home/vagrant/ctypegen/test'
python2 ./CTypeGenSanity.py ./CTypeSanity
Traceback (most recent call last):
  File "./CTypeGenSanity.py", line 16, in <module>
    from CTypeGen import generate, PythonType, generateOrThrow
  File "/usr/local/lib/python2.7/dist-packages/CTypeGen.py", line 18, in <module>
    import PyDwarfWrapper
  File "/usr/local/lib/python2.7/dist-packages/PyDwarfWrapper.py", line 15, in <module>
    import libCTypeGen
ImportError: /usr/local/lib/python2.7/dist-packages/libCTypeGen.so: undefined symbol: lzma_stream_footer_decode
Makefile:29: recipe for target 'check' failed
make[1]: *** [check] Error 1
make[1]: Leaving directory '/home/vagrant/ctypegen/test'
Makefile:24: recipe for target 'test' failed
make: *** [test] Error 2
`
Here is extensions build log, don't see any issues though: 
`vagrant@ubuntu-xenial:~/ctypegen$ make VERBOSE=1
env CFLAGS="-g -O0 --std=c++14" /usr/bin/python2 ./setup.py build
running build
running build_py
creating build
creating build/lib.linux-i686-2.7
copying CTypeGen.py -> build/lib.linux-i686-2.7
copying CMock.py -> build/lib.linux-i686-2.7
copying PyDwarfWrapper.py -> build/lib.linux-i686-2.7
copying CTypeGenRun.py -> build/lib.linux-i686-2.7
running build_ext
building 'libCTypeGen' extension
creating build/temp.linux-i686-2.7
i686-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O0 --std=c++14 -fPIC -I/usr/include/python2.7 -c CTypeGen.cpp -o build/temp.linux-i686-
2.7/CTypeGen.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOUR
CE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -g -O0 --std=c++14 build/temp.linux-i686-2.7/CTypeGen.o -ldwelf -o build/lib.linux-i68
6-2.7/libCTypeGen.so
building 'libCTypeMock' extension
i686-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O0 --std=c++14 -fPIC -I/usr/include/python2.7 -c cmock.cpp -o build/temp.linux-i686-2.7
/cmock.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOUR
CE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -g -O0 --std=c++14 build/temp.linux-i686-2.7/cmock.o -ldwelf -o build/lib.linux-i686-2
.7/libCTypeMock.so
`

**Comment by peadar** [comment]
I think the most likely cause of this is that you've got statically linked
libraries from "pstack", rather than dynamic ones. (You need to configure
pstack like this:

$ cmake -DCMAKE_BUILD_TYPE=Release LIBTYPE=SHARED .

If you have static libraries, you could add the transitive dependencies
from the pstack libs to the link line (-lzma -lz at least), but it's
generally not a good idea to link static libs into shared libs like that.
Let me know if you still have problems.

**Comment by sbryskyi** [comment]
Hi Peter, thanks for the quick answer. You were right, shared lib was not produced.
In my case, it didn't work initially due to incorrect cmake cache entry syntax.
I had to change your line to: $ cmake -DCMAKE_BUILD_TYPE=Release, **-D**LIBTYPE=SHARED . 
so it follows:  -D <var>:<type>=<value>, -D <var>=<value> syntax
Please update README.md if applicable.
Thanks for the help.
