### ISSUE TITLE
make test failed

### ISSUE THREAD

**Issue by nguyenlam185** [aristanetworks/ctypegen#3]
Hello,
I have clone your repo and follow the guidelines. Everything is fine until I reached to the line `make test`
I have tried with make PYTHON=python3 test and it was also fail. Following is the error messages
`make test`
`Running tests...`
`Test project /home/primeuser/bob/workspace/pstack`
`    Start 1: basic`
`1/5 Test #1: basic ............................***Failed    0.08 sec`
`    Start 2: segv`
`2/5 Test #2: segv .............................***Failed    0.08 sec`
`    Start 3: thread`
`3/5 Test #3: thread ...........................***Failed    0.08 sec`
`    Start 4: badfp`
`4/5 Test #4: badfp ............................***Failed    0.08 sec`
`    Start 5: asserttext`
`5/5 Test #5: asserttext .......................***Failed    0.01 sec`

`0% tests passed, 5 tests failed out of 5`

`Total Test time (real) =   0.34 sec`

`The following tests FAILED:`
`	  1 - basic (Failed)`
`	  2 - segv (Failed)`
`	  3 - thread (Failed)`
`	  4 - badfp (Failed)`
`	  5 - asserttext (Failed)`
`Errors while running CTest`
`Makefile:129: recipe for target 'test' failed`
`make: *** [test] Error 8`

Does it impact to anything? Because after that, I cannot run the setup.py script too. It ends up with the message
`sudo python3 setup.py build`
`running build`
`running build_py`
`running build_ext`
`building 'libCTypeMock' extension`
`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include -I/usr/include/python3.6m -c cmock.cpp -o build/temp.linux-x86_64-3.6/cmock.o`
`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include -I/usr/include/python3.6m -c thunk-b'x86_64'.s -o build/temp.linux-x86_64-3.6/thunk-b'x86_64'.o`
`x86_64-linux-gnu-gcc: error: thunk-b'x86_64'.s: No such file or directory`
`x86_64-linux-gnu-gcc: fatal error: no input files`
`compilation terminated.`
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

Please tell me what should I do to solve this issue

**Comment by peadar** [comment]
Hey,
The problem with the tests in pstack should not be an issue - the tests only work if you have a debug build, and if your system has a value for `kernel.core_pattern` that the test drivers can decipher, so they can open the core files generated by the tests. I'll clean up the tests when time permits, but don't worry about that failure. 

For the build issue for ctypegen when using python3, I've just pushed a fix for this and another minor python3-related problem. Please let me know if this resolves the issue

**Comment by nguyenlam185** [comment]
Hi peadar,
It works for me. Now I can run `setup.py build` and `setup.py install` as well.
Thanks for you effort fixing this issue :+1:

**Comment by peadar** [comment]
Great, thanks for the report!

**Comment by reikdas** [comment]
I get the same error.

The tests fail - 
```
[reik@reik-msi pstack]$ make PYTHON=python3 test
Running tests...
Test project /home/reik/pstack
    Start 1: args
1/7 Test #1: args .............................***Failed    0.32 sec
    Start 2: badfp
2/7 Test #2: badfp ............................***Failed    0.28 sec
    Start 3: basic
3/7 Test #3: basic ............................***Failed    0.30 sec
    Start 4: cpp
4/7 Test #4: cpp ..............................***Failed    0.28 sec
    Start 5: noreturn
5/7 Test #5: noreturn .........................***Failed    0.28 sec
    Start 6: segv
6/7 Test #6: segv .............................***Failed    0.28 sec
    Start 7: thread
7/7 Test #7: thread ...........................***Failed    0.34 sec

0% tests passed, 7 tests failed out of 7

Total Test time (real) =   2.09 sec

The following tests FAILED:
	  1 - args (Failed)
	  2 - badfp (Failed)
	  3 - basic (Failed)
	  4 - cpp (Failed)
	  5 - noreturn (Failed)
	  6 - segv (Failed)
	  7 - thread (Failed)
Errors while running CTest
make: *** [Makefile:150: test] Error 8
```

and setup.py fails - 
```
[reik@reik-msi ctypegen]$ python setup.py install
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.8
copying CTypeGen.py -> build/lib.linux-x86_64-3.8
copying CMock.py -> build/lib.linux-x86_64-3.8
copying CTypeGenRun.py -> build/lib.linux-x86_64-3.8
running build_ext
building 'libCTypeGen' extension
creating build/temp.linux-x86_64-3.8
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/local/include -I/usr/include/python3.8 -c CTypeGen.cpp -o build/temp.linux-x86_64-3.8/CTypeGen.o
g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fno-semantic-interposition -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-x86_64-3.8/CTypeGen.o -L/usr/local/lib -L/usr/lib -ldwelf -o build/lib.linux-x86_64-3.8/libCTypeGen.cpython-38-x86_64-linux-gnu.so
building 'libCTypeMock' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/local/include -I/usr/include/python3.8 -c cmock.cpp -o build/temp.linux-x86_64-3.8/cmock.o
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/local/include -I/usr/include/python3.8 -c thunk-unknown.s -o build/temp.linux-x86_64-3.8/thunk-unknown.o
gcc: error: thunk-unknown.s: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 1
```
and
```
[reik@reik-msi ctypegen]$ python setup.py build
running build
running build_py
running build_ext
building 'libCTypeMock' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/local/include -I/usr/include/python3.8 -c cmock.cpp -o build/temp.linux-x86_64-3.8/cmock.o
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/local/include -I/usr/include/python3.8 -c thunk-unknown.s -o build/temp.linux-x86_64-3.8/thunk-unknown.o
gcc: error: thunk-unknown.s: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 1

```

**Comment by peadar** [comment]
Hey -
The errors from testing pstack can be ignored (the tests will only work on
a debug build if the kernel.core_pattern is set to something parseable by
the python wrapper code)

The compilation error you're seeing in ctypegen seems to be a result of the
build being unable to work out the platform for your host - setup.py uses
`uname -i` to work out what platform you are running on, and selects either
the x86_64 or i386 "thunk" file to incorporate. What do "uname -a" and
"uname -i" report for you? What linux distribution are you using?
You could hard-code `arch` to be `x86_64` in setup.py to get over the
problem, but it'd be nice to fix this for others, of course.

**Comment by reikdas** [comment]
> What do "uname -a" and "uname -i" report for you?

```
[reik@reik-msi ~]$ uname -i
unknown
```

```
[reik@reik-msi ~]$ uname -a
Linux reik-msi 5.4.44-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:48:07 UTC 2020 x86_64 GNU/Linux
```

> What linux distribution are you using?

Manjaro

> You could hard-code `arch` to be `x86_64` in setup.py to get over the problem

That worked. Thanks!
